### ISSUE TITLE
Error on GSTR-1 beta Upload

### ISSUE THREAD

**Issue by innomalous** [resilient-tech/india-compliance#3420]
### Information about bug

I'm using the GSTR-1 Beta report to compute and upload my GST sales invoices.
But getting the following error on "Upload": KeyError: 'document_type' Possible source of error: india_compliance (app)

![Image](https://github.com/user-attachments/assets/9ef9a80d-64d4-46aa-ac2f-fd8c1d18b968)

Tried with Admin account too, still same error.

### Version

"erpnext": "15.63.0",
	"frappe": "15.69.2",
	"hrms": "15.45.3",
	"india_compliance": "15.18.0",
	"lending": "0.0.1",
	"payments": "0.0.1"

### Relevant log output / Stack trace / Full Error Message.

```shell
### App Versions

{
	"erpnext": "15.63.0",
	"frappe": "15.69.2",
	"hrms": "15.45.3",
	"india_compliance": "15.18.0",
	"lending": "0.0.1",
	"payments": "0.0.1"
}

### Route

Form/GSTR-1 Beta/GSTR-1 Beta

### Traceback

Traceback (most recent call last):
  File "apps/frappe/frappe/app.py", line 115, in application
    response = frappe.api.handle(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/__init__.py", line 49, in handle
    data = endpoint(**arguments)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/api/v1.py", line 36, in handle_rpc_call
    return frappe.handler.handle()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 51, in handle
    data = execute_cmd(cmd)
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/handler.py", line 84, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/__init__.py", line 1742, in call
    return fn(*args, **newargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/api_classes/taxpayer_base.py", line 43, in wrapper
    raise e
  File "apps/india_compliance/india_compliance/gst_india/api_classes/taxpayer_base.py", line 34, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_beta.py", line 199, in perform_gstr1_action
    data = get_gstr_1_json(
           ^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/utils/typing_validations.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/doctype/gstr_1_beta/gstr_1_export.py", line 2122, in get_gstr_1_json
    **convert_to_gov_data_format(data, company_gstin),
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py", line 1953, in convert_to_gov_data_format
    output[category] = mapper_class().convert_to_gov_data_format(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/india_compliance/india_compliance/gst_india/utils/gstr_1/gstr_1_json_map.py", line 1231, in convert_to_gov_data_format
    doc_type = invoice[GSTR1_DataField.DOC_TYPE.value]
               ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'document_type'


### Request Data

{
	"type": "POST",
	"args": {
		"month_or_quarter": "May",
		"year": "2025",
		"company_gstin": "09AAECI1177P1Z1",
		"action": "upload_gstr1",
		"force": false
	},
	"headers": {},
	"error_handlers": {},
	"url": "/api/method/india_compliance.gst_india.doctype.gstr_1_beta.gstr_1_beta.perform_gstr1_action",
	"request_id": "c3050463-90ce-4851-8f47-cc23e45d313c"
}

### Response Data

{
	"exception": "KeyError: 'document_type'",
	"exc_type": "KeyError",
	"_exc_source": "india_compliance (app)"
}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ljain112** [comment]
Sorry for the inconvenience caused.
We will fix the issue and inform you once fix has been released.

**Comment by vorasmit** [comment]
I guess this should'nt be an issue on the latest: v15.18.1

Can you please check if this exists on latest?

**Comment by ljain112** [comment]
Issue is resolved in the latest version: v15.18.1

**Comment by innomalous** [comment]
Hello, updated to v15.18.1.

Now getting a new error: Error in Json structure validation.

![Image](https://github.com/user-attachments/assets/8d02e462-13c4-431a-b875-f7bd259c7b2d)

Tried to download the json and upload manually in the GST portal. Got the following error:
File could not be uploaded! Download the latest version of Offline tool to generate the JSON file or ensure to validate your uploaded file against the template published at Specification Portal.

![Image](https://github.com/user-attachments/assets/4df845c1-8f46-4e4f-ac0c-3510f4aa7d29)

**Comment by vorasmit** [comment]
Hi, this is likely because json you tried uploading may have been generated before you updated the server.

Can you re-compute books data and try again?

**Comment by innomalous** [comment]
I clicked "reset", and recreated the books. Still the same issue with json structure.

![Image](https://github.com/user-attachments/assets/73f7d262-493b-4fcc-9151-215915743189)

![Image](https://github.com/user-attachments/assets/f3c6704e-d308-4094-91a3-184a44490f13)

Am I doing this right?

**Comment by vorasmit** [comment]
Steps specified here.

![Image](https://github.com/user-attachments/assets/b03be4ab-1dde-4f00-ac41-8659dae0d086)

**Comment by innomalous** [comment]
It worked this time. Thank you so much. 👍🏻
