### ISSUE TITLE
Issue while PURCHASE ORDER creation 

### ISSUE THREAD

**Issue by NayabChauhan** [resilient-tech/india-compliance#935]
### Information about bug

Subject: Issue with INDIAN GST COMPLIANCE MODULE Integration in ErpNext

Dear Team,

I hope this email finds you well. I am writing to bring to your attention an issue that we have encountered during the integration of the INDIAN GST COMPLIANCE MODULE into our ErpNext system.

We have diligently ensured that we are using the latest versions of all relevant modules for this integration, as outlined below:

- ErpNext: 14.33.2
- Frappe: 14.43.1
- HRMS: 14.10.0
- India Compliance: 14.14.0
- Payments: 0.0.1

Despite our efforts, we are encountering a persistent error message when attempting to submit a purchase order. The error states that "Company GSTIN is mandatory," even though we have meticulously provided all the requisite data within the company settings.

To provide a comprehensive overview of the issue, I have attached a document to this email that includes relevant details and screenshots. We kindly request your assistance in diagnosing and resolving this matter as swiftly as possible, as it is currently impeding our workflow and procurement processes.

Your expertise and support are highly valued. We remain committed to ensuring the seamless functioning of our ErpNext system and the successful integration of the INDIAN GST COMPLIANCE MODULE.

Thank you for your attention to this matter. We look forward to your prompt response.

Best regards,
NAYAB

### Version

ErpNext: 14.33.2
Frappe: 14.43.1
HRMS: 14.10.0
India Compliance: 14.14.0
Payments: 0.0.1
[issue.pdf](https://github.com/resilient-tech/india-compliance/files/12278360/issue.pdf)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vorasmit** [comment]
Traceback is important and crucial to help resolve the bug.
https://stackoverflow.com/questions/36503244/how-to-copy-a-stack-trace-from-the-chrome-console

What is the default country as per Global Defaults? If its not `India`, maybe I know the issue and is already fixed in very recent versions after v14.14.0. Update it to v14.14.4.

**Comment by NayabChauhan** [comment]
Hello,

still the same error please check attached screenshot
![Global-Defaults](https://github.com/resilient-tech/india-compliance/assets/45756499/a433147f-154d-4af8-8aab-cdca2b21868c)

**Comment by vorasmit** [comment]
Nayab,

The issue is probably with how the system is configured. As asked earlier, tracebacks are very important for us to check for the issue and comment further.

If the issue is with configuration as it looks like, this is not the correct forum to raise the issue and you can take it forward and you may please consider posting this on discuss forum for help from community members (https://discuss.frappe.io/c/erpnext/india-compliance/65) or consider purchasing support (email us at support@indiacompliance.app for more info).

Closing this issue for now. We'll reopen once it's confirmed with additional evidence.
